[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/var/run/supervisord.pid

[program:mariadb]
command=/usr/bin/mysqld_safe --datadir=/var/lib/mysql
priority=10
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:redis]
command=/usr/bin/redis-server /etc/redis/redis.conf
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:web]
directory=/home/frappe/frappe-bench
command=/bin/bash -lc "sleep 15 && bench serve --host 0.0.0.0 --port 8000"
user=frappe
priority=30
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=HOME="/home/frappe",USER="frappe"

[program:worker]
directory=/home/frappe/frappe-bench
command=/bin/bash -lc "sleep 20 && bench worker"
user=frappe
priority=40
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=HOME="/home/frappe",USER="frappe"

[program:schedule]
directory=/home/frappe/frappe-bench
command=/bin/bash -lc "sleep 25 && bench schedule"
user=frappe
priority=50
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=HOME="/home/frappe",USER="frappe"
